-- On click/touch get touch position and send it via message to hud gui script as well as the scored point amount.

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	local pos = vmath.vector3(action.x, action.y, 0) -- use input action.x & action.y as x & y positions of touch
	if action_id == hash("touch") then
		if action.pressed then
			msg.post("main:/hud#hud", "add_score" , { position = pos, amount = 1500})
		end
	end
end